
INSERT ALL
  
  INTO Departments VALUES('CSE', 'Computer Science and Engineering')
  
  INTO Programmes VALUES('CE', 'Computer Engineering')
  INTO Programmes VALUES('IT', 'Information Technology')
  
  INTO Departments_Programmes VALUES('CSE', 'CE')
  INTO Departments_Programmes VALUES('CSE', 'IT')
  
  INTO Branches VALUES('CE', 'Computer Languages')
  INTO Branches VALUES('IT', 'Distributed Computing')
  
  INTO Courses VALUES('TMV216', 'Linear Algebra', 10, 'CSE')
  INTO Courses VALUES('TMV170', 'Calculus', 10, 'CSE')
  INTO Courses VALUES('TDA357', 'Databases', 10, 'CSE')
  INTO Courses VALUES('DAT076', 'Web Applications', 10, 'CSE')
  INTO Courses VALUES('TIN092', 'Algorithms', 10, 'CSE')
  INTO Courses VALUES('TIN172', 'Artificial Intelligence', 10, 'CSE')
  
  INTO Limited_Courses VALUES('TDA357', 5)
  INTO Limited_Courses VALUES('DAT076', 4)
  INTO Limited_Courses VALUES('TIN092', 5)
  INTO Limited_Courses VALUES('TIN172', 4)
  
  INTO Classifications VALUES('mathematical')
  INTO Classifications VALUES('research')
  INTO Classifications VALUES('seminar')
  
  INTO Course_Classifications VALUES('TMV216', 'mathematical')
  INTO Course_Classifications VALUES('TMV170', 'mathematical')
  INTO Course_Classifications VALUES('TDA357', 'research')
  INTO Course_Classifications VALUES('TIN092', 'research')
  INTO Course_Classifications VALUES('DAT076', 'research')
  INTO Course_Classifications VALUES('TIN172', 'research')
  INTO Course_Classifications VALUES('TDA357', 'seminar')
  INTO Course_Classifications VALUES('TIN092', 'seminar')
  
  INTO Course_Prerequisites VALUES('TMV170', 'TMV216')
  INTO Course_Prerequisites VALUES('TIN172', 'TIN092')
  
  INTO Programme_Requirements VALUES('CE', 'TMV216')
  INTO Programme_Requirements VALUES('CE', 'TMV170')
  INTO Programme_Requirements VALUES('IT', 'TMV216')
  INTO Programme_Requirements VALUES('IT', 'TMV170')
  
  INTO Branch_Requirements VALUES('CE', 'Computer Languages', 'TIN092')
  INTO Branch_Requirements VALUES('IT', 'Distributed Computing', 'TDA357')
  
  INTO Branch_Recommendations VALUES('CE', 'Computer Languages', 'TIN172')
  INTO Branch_Recommendations VALUES('IT', 'Distributed Computing', 'DAT076')
  
  INTO Students VALUES('leoeng', 'Leonard Engh', 'CE', 'Computer Languages')
  INTO Students VALUES('eulpet', 'Eulah Pettaway', 'CE', 'Computer Languages')
  INTO Students VALUES('grajas', 'Gracia Jaso', 'CE', 'Computer Languages')
  INTO Students VALUES('antrev', 'Antonette Revard', 'CE', 'Computer Languages')
  INTO Students VALUES('rebrei', 'Rebekah Reisinger', 'CE', 'Computer Languages')
  INTO Students VALUES('reghil', 'Reginald Hiller', 'CE', 'Computer Languages')
  INTO Students VALUES('clabro', 'Clarisa Broderson', 'CE', 'Computer Languages')
  INTO Students VALUES('emebar', 'Emery Barney', 'CE', 'Computer Languages')
  INTO Students VALUES('adeper', 'Adelle Perron', 'CE', 'Computer Languages')
  INTO Students VALUES('maggal', 'Margery Gallant', 'CE', 'Computer Languages')
  INTO Students VALUES('archod', 'Archie Hodges', 'CE', 'Computer Languages')
  INTO Students VALUES('chayed', 'Charlott Yedinak', 'CE', 'Computer Languages')
  INTO Students VALUES('erlroe', 'Erlinda Roehl', 'CE', 'Computer Languages')
  INTO Students VALUES('carpet', 'Carlena Petsche', 'CE', 'Computer Languages')
  INTO Students VALUES('frador', 'Francis Dorner', 'CE', 'Computer Languages')
  INTO Students VALUES('ausval', 'Austin Vallery', 'CE', 'Computer Languages')
  INTO Students VALUES('nentho', 'Nenita Thompkins', 'CE', 'Computer Languages')
  INTO Students VALUES('scolen', 'Scott Lenox', 'CE', 'Computer Languages')
  INTO Students VALUES('verlot', 'Vernia Lotts', 'IT', 'Distributed Computing')
  INTO Students VALUES('chafla', 'Charley Flakes', 'IT', 'Distributed Computing')
  INTO Students VALUES('louniv', 'Lourdes Niver', 'IT', 'Distributed Computing')
  INTO Students VALUES('catnov', 'Catherine Novotny', 'IT', 'Distributed Computing')
  INTO Students VALUES('carmol', 'Carlo Mollett', 'IT', 'Distributed Computing')
  INTO Students VALUES('cedarr', 'Cedric Arrington', 'IT', 'Distributed Computing')
  INTO Students VALUES('berrep', 'Bernardo Replogle', 'IT', 'Distributed Computing')
  INTO Students VALUES('shakug', 'Shani Kugel', 'IT', 'Distributed Computing')
  INTO Students VALUES('marchi', 'Mariann Chickering', 'IT', 'Distributed Computing')
  INTO Students VALUES('owespa', 'Owen Sparano', 'IT', 'Distributed Computing')
  INTO Students VALUES('walbro', 'Wally Brode', 'IT', 'Distributed Computing')
  INTO Students VALUES('denpat', 'Denna Patchen', 'IT', 'Distributed Computing')
  
  /* CE - Year 1 */
  INTO Students_Courses VALUES('leoeng', 'TMV216')
  INTO Students_Courses VALUES('leoeng', 'TIN092')
  INTO Students_Courses VALUES('eulpet', 'TMV216')
  INTO Students_Courses VALUES('eulpet', 'TIN092')
  INTO Students_Courses VALUES('grajas', 'TMV216')
  INTO Students_Courses VALUES('grajas', 'TIN092')
  INTO Students_Courses VALUES('antrev', 'TMV216')
  INTO Students_Courses VALUES('antrev', 'TIN092')
  INTO Students_Courses VALUES('rebrei', 'TMV216')
  INTO Students_Courses VALUES('rebrei', 'TIN092')
  INTO Students_Courses VALUES('reghil', 'TMV216')
--INTO Students_Courses VALUES('reghil', 'TIN092') in queue!
  /* CE - Year 2 */
  INTO Students_Courses VALUES('clabro', 'TMV170')
  INTO Students_Courses VALUES('clabro', 'TIN172')
  INTO Students_Courses VALUES('emebar', 'TMV170')
  INTO Students_Courses VALUES('emebar', 'TIN172')
  INTO Students_Courses VALUES('adeper', 'TMV170')
  INTO Students_Courses VALUES('adeper', 'TIN172')
  INTO Students_Courses VALUES('maggal', 'TMV170')
  INTO Students_Courses VALUES('maggal', 'TIN172')
  INTO Students_Courses VALUES('archod', 'TMV170')
  INTO Students_Courses VALUES('archod', 'TDA357')
  INTO Students_Courses VALUES('chayed', 'TMV170')
  INTO Students_Courses VALUES('chayed', 'TDA357') --Makes course overfull
  /* IT - Year 1 */
  INTO Students_Courses VALUES('verlot', 'TMV216')
  INTO Students_Courses VALUES('verlot', 'TDA357')
  INTO Students_Courses VALUES('chafla', 'TMV216')
  INTO Students_Courses VALUES('chafla', 'TDA357')
  INTO Students_Courses VALUES('louniv', 'TMV216')
  INTO Students_Courses VALUES('louniv', 'TDA357')
  INTO Students_Courses VALUES('catnov', 'TMV216')
  INTO Students_Courses VALUES('catnov', 'TDA357')
  /* IT - Year 2 */
  INTO Students_Courses VALUES('carmol', 'TMV170')
  INTO Students_Courses VALUES('carmol', 'DAT076')
  INTO Students_Courses VALUES('cedarr', 'TMV170')
  INTO Students_Courses VALUES('cedarr', 'DAT076')
  INTO Students_Courses VALUES('berrep', 'TMV170')
  INTO Students_Courses VALUES('berrep', 'DAT076')
  INTO Students_Courses VALUES('shakug', 'TMV170')
--INTO Students_Courses VALUES('shakug', 'TIN092') in queue!
  
  /* CE - Year 2 */
  INTO Student_Grades VALUES('clabro', 'TMV216', '4')
  INTO Student_Grades VALUES('clabro', 'TIN092', '3')
  INTO Student_Grades VALUES('emebar', 'TMV216', 'U')
  INTO Student_Grades VALUES('emebar', 'TIN092', '3')
  INTO Student_Grades VALUES('adeper', 'TMV216', '4')
  INTO Student_Grades VALUES('adeper', 'TIN092', 'U')
  INTO Student_Grades VALUES('maggal', 'TMV216', '3')
  INTO Student_Grades VALUES('maggal', 'TIN092', '3')
  INTO Student_Grades VALUES('archod', 'TMV216', '4')
  INTO Student_Grades VALUES('archod', 'TIN092', '3')
  INTO Student_Grades VALUES('chayed', 'TMV216', '5')
  INTO Student_Grades VALUES('chayed', 'TIN092', '5')
  /* CE - Year 3 */
  INTO Student_Grades VALUES('erlroe', 'TMV216', '3')
  INTO Student_Grades VALUES('erlroe', 'TMV170', '4')
  INTO Student_Grades VALUES('erlroe', 'TIN092', '4')
  INTO Student_Grades VALUES('erlroe', 'TIN172', '3')
  INTO Student_Grades VALUES('carpet', 'TMV216', '4')
  INTO Student_Grades VALUES('carpet', 'TMV170', '3')
  INTO Student_Grades VALUES('carpet', 'TIN092', '3')
  INTO Student_Grades VALUES('carpet', 'TIN172', 'U')
  INTO Student_Grades VALUES('frador', 'TMV216', '3')
  INTO Student_Grades VALUES('frador', 'TMV170', '3')
  INTO Student_Grades VALUES('frador', 'TIN092', '5')
  INTO Student_Grades VALUES('frador', 'TIN172', '4')
  INTO Student_Grades VALUES('ausval', 'TMV216', '5')
  INTO Student_Grades VALUES('ausval', 'TMV170', '3')
  INTO Student_Grades VALUES('ausval', 'TIN092', '4')
  INTO Student_Grades VALUES('ausval', 'TIN172', '3')
  INTO Student_Grades VALUES('nentho', 'TMV216', '3')
  INTO Student_Grades VALUES('nentho', 'TMV170', '3')
  INTO Student_Grades VALUES('nentho', 'TIN092', '3')
  INTO Student_Grades VALUES('nentho', 'TIN172', 'U')
  INTO Student_Grades VALUES('scolen', 'TMV216', '3')
  INTO Student_Grades VALUES('scolen', 'TMV170', 'U')
  INTO Student_Grades VALUES('scolen', 'TIN092', '4')
  INTO Student_Grades VALUES('scolen', 'TIN172', '3')
  /* IT - Year 2 */
  INTO Student_Grades VALUES('carmol', 'TMV216', '3')
  INTO Student_Grades VALUES('carmol', 'TDA357', '5')
  INTO Student_Grades VALUES('cedarr', 'TMV216', '4')
  INTO Student_Grades VALUES('cedarr', 'TDA357', '5')
  INTO Student_Grades VALUES('berrep', 'TMV216', 'U')
  INTO Student_Grades VALUES('berrep', 'TDA357', '3')
  INTO Student_Grades VALUES('shakug', 'TMV216', '3')
  INTO Student_Grades VALUES('shakug', 'TDA357', '4')
  /* IT - Year 3 */
  INTO Student_Grades VALUES('marchi', 'TMV216', '3')
  INTO Student_Grades VALUES('marchi', 'TMV170', '4')
  INTO Student_Grades VALUES('marchi', 'TDA357', '5')
  INTO Student_Grades VALUES('marchi', 'DAT076', '4')
  INTO Student_Grades VALUES('owespa', 'TMV216', '3')
  INTO Student_Grades VALUES('owespa', 'TMV170', '3')
  INTO Student_Grades VALUES('owespa', 'TDA357', '4')
  INTO Student_Grades VALUES('owespa', 'DAT076', '3')
  INTO Student_Grades VALUES('walbro', 'TMV216', '3')
  INTO Student_Grades VALUES('walbro', 'TMV170', 'U')
  INTO Student_Grades VALUES('walbro', 'TDA357', '3')
  INTO Student_Grades VALUES('walbro', 'DAT076', 'U')
  INTO Student_Grades VALUES('denpat', 'TMV216', '4')
  INTO Student_Grades VALUES('denpat', 'TMV170', '3')
  INTO Student_Grades VALUES('denpat', 'TDA357', '3')
  INTO Student_Grades VALUES('denpat', 'DAT076', '4')
  
SELECT * FROM DUAL;

INSERT INTO Course_Queues VALUES('TIN092', 'reghil', Queue_Counter.nextval);
INSERT INTO Course_Queues VALUES('TIN092', 'shakug', Queue_Counter.nextval);
